### PR TITLE
Implement `Channel::username()`

### PR DESCRIPTION
**Pull request by AndrielFR**
With this, you can use `channel.username()` to get a megagroup/channel username.

### CODE REVIEW

**Comment by Lonami** [comment]
The current CI error is unrelated to this change. However I'd like to see this method added for `Chat` and `Group` as well before merging (`User` already has it). Would you be willing to add these?

**Comment by AndrielFR** [comment]
> The current CI error is unrelated to this change. However I'd like to see this method added for `Chat` and `Group` as well before merging (`User` already has it). Would you be willing to add these?

Done. (?)

**Comment by Lonami** [comment]
Excellent, thanks!

**Comment by AndrielFR** [comment]
> Excellent, thanks!

🤝

**Pull request merged**
