### PR TITLE
Add PackedChat::to_bytes and PackedChat::from_bytes

### PR DESCRIPTION
**Pull request by the-blank-x**

### CODE REVIEW

**Comment by Lonami** [comment]
Just realized the downside to this is that we have no way of knowing if a `Channel` is a `megagroup` or a `broadcast` (and I guess `gigagroup` now too). It would also probably be useful to store if the user is a bot or not.

**Comment by the-blank-x** [comment]
Are there perks of knowing a channel is a megagroup, broadcast or gigagroup, or that a user is a bot?

**Comment by Lonami** [comment]
At the very least, we need megagroup/broadcast, because when constructing the `Chat` we differentiate between groups or broadcast channels.

**Comment by Lonami** [comment]
Note that I've already fixed this locally, just didn't push yet.

**Pull request merged**
