### PR TITLE
Make PasswordToken cloneable

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Review by Lonami — COMMENTED** [review]
Why is this change needed?

**Review by Paryyysaa — APPROVED** [review]

**Comment by Lonami** [comment]
Good point. I would prefer if another solution was chosen, though, as making cloneable defeats the purpose of "making invalid states irrepresentable" (here, being able to use the token freely, even after successful sign-in).

What we should do is change the return type of `check_password` so that it includes the token every time. Then you can reuse the token if and only if the method failed and you're not logged in.

But I know that's a pain.

So please at least add:

```rs
// TODO this should not be Clone, but check_password Err doesn't include it back yet
```

above the change so we can remember to address it in the future. And then we can merge this temporary workaround.

(Unless you want to implement the better `Err`. That's the better solution.)

**Comment by roj1512** [comment]
> `check_password Err doesn't include it back yet`

`check_password` error or `SignInError::PasswordInvalid`?

**Comment by Lonami** [comment]
The `Error` type used in `check_password`'s `Err` variant should probably be a new `enum` specific to that method.

We probably want something as discussed in https://t.me/gramme_rs/17454. But that can come later. I'm happy with adding the TODO for now.

**Comment by roj1512** [comment]
Done!

**Pull request merged**
