### PR TITLE
Add a method to allow using TL types for media in InputMessage 

### PR DESCRIPTION
**Pull request by er-azh**
Adds two new methods to `InputMessage` , `photo_id` and `document_id`. These new methods allow the user to include media in their messages using `InputPhoto` and `InputDocument` without having to copy the media from a message or re-uploading.

### CODE REVIEW

**Review by Lonami — COMMENTED** [review]
I'm not convinced on the naming. Would be nice to accept a generic for either `Uploaded` or the input version.

**Comment by er-azh** [comment]
Hmmm, what about adding something like this and then adding `into_document` and `into_photo` to `Uploaded` instead?
```rust
pub fn media<T: Into<tl::enums::InputMedia>>(mut self, media: T) -> Self {
    self.media = Some(media.into());
    self
}
```
The issue with using a generic parameter for the current `document` and `photo` methods is that I can't think of a way to differentiate between the media types (eg. `InputMediaPhoto` and `InputMediaDocument`) while accepting both uploaded and forwarded variants of `InputMedia` (eg. `InputMediaPhoto` and `InputMediaUploadedPhoto`) without adding at least one unnecessary wrapper type.

**Comment by Lonami** [comment]
I was thinking of two traits, `IntoInputPhoto` and `IntoInputDocument`, both implemented for `Uploaded`, but only one for the raw types.

**Comment by er-azh** [comment]
I've updated everything based on the telegram discussion.

**Pull request merged**
